Chnaged githhub link

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -38,7 +38,7 @@ jobs:
             # Check if the project directory exists on the server
             if [ ! -d "/home/ubuntu/my-app/.git" ]; then
               echo "Directory doesn't exist. Cloning repository..."
-              git clone git@github.com:2003deepak/CC-Lab.git /home/ubuntu/my-app || { echo "Clone failed"; exit 1; }
+              git clone https://github.com/2003deepak/CC-Lab.git /home/ubuntu/my-app || { echo "Clone failed"; exit 1; }
               cd /home/ubuntu/my-app || { echo "Directory not found after clone"; exit 1; }
             else
               echo "Directory exists. Pulling latest changes..."
